<?php

declare(strict_types=1);

namespace BenRowe\StateFlow\Tests\Unit;

use BenRowe\StateFlow\Action\Action;
use BenRowe\StateFlow\ActionSkip;
use BenRowe\StateFlow\Gate\GateResult;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

class ActionSkipTest extends TestCase
{
    private Action $mockAction;

    protected function setUp(): void
    {
        parent::setUp();
        $this->mockAction = $this->createStub(Action::class);
    }

    // Construction Tests

    public function testConstructWithAutoGeneratedTimestamp(): void
    {
        $skip = new ActionSkip(
            $this->mockAction,
            GateResult::DENY
        );

        $this->assertGreaterThan(0, $skip->timestamp);
    }

    public function testConstructWithExplicitTimestamp(): void
    {
        $explicitTimestamp = 1234567890.123456;

        $skip = new ActionSkip(
            $this->mockAction,
            GateResult::DENY,
            $explicitTimestamp
        );

        $this->assertSame($explicitTimestamp, $skip->timestamp);
    }

    // Timestamp Behavior Tests

    public function testAutoTimestampIsReasonable(): void
    {
        $before = microtime(true);
        $skip = new ActionSkip(
            $this->mockAction,
            GateResult::DENY
        );
        $after = microtime(true);

        $this->assertGreaterThanOrEqual($before, $skip->timestamp);
        $this->assertLessThanOrEqual($after, $skip->timestamp);
    }

    public function testExplicitTimestampPreserved(): void
    {
        $explicitTimestamp = 1609459200.987654; // 2021-01-01 00:00:00.987654

        $skip = new ActionSkip(
            $this->mockAction,
            GateResult::SKIP_IDEMPOTENT,
            $explicitTimestamp
        );

        $this->assertSame($explicitTimestamp, $skip->timestamp, 'Explicit timestamp should be preserved exactly');
    }

    public function testMultipleInstancesHaveDifferentTimestamps(): void
    {
        $skip1 = new ActionSkip(
            $this->mockAction,
            GateResult::DENY
        );

        // Small delay to ensure different timestamps
        usleep(100); // 0.0001 seconds

        $skip2 = new ActionSkip(
            $this->mockAction,
            GateResult::DENY
        );

        $this->assertNotEquals(
            $skip1->timestamp,
            $skip2->timestamp,
            'Auto-generated timestamps should differ for instances created at different times'
        );
        $this->assertLessThan($skip2->timestamp, $skip1->timestamp);
    }

    // Readonly Immutability Tests

    public function testAllPropertiesArePublic(): void
    {
        $skip = new ActionSkip(
            $this->mockAction,
            GateResult::DENY
        );

        // Should be able to read all properties
        $this->assertInstanceOf(Action::class, $skip->action);
        $this->assertSame(GateResult::DENY, $skip->gateResult);
        $this->assertGreaterThan(0, $skip->timestamp);
    }

    public function testIsReadonlyClass(): void
    {
        $reflection = new ReflectionClass(ActionSkip::class);

        $this->assertTrue(
            $reflection->isReadOnly(),
            'ActionSkip should be a readonly class'
        );
    }
}
