<?php

declare(strict_types=1);

namespace BenRowe\StateFlow\Tests\Unit;

use BenRowe\StateFlow\Gate\Gate;
use BenRowe\StateFlow\Gate\GateResult;
use BenRowe\StateFlow\GateEvaluation;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

class GateEvaluationTest extends TestCase
{
    private Gate $mockGate;

    protected function setUp(): void
    {
        parent::setUp();
        $this->mockGate = $this->createStub(Gate::class);
    }

    // Construction Tests

    public function testConstructWithAutoGeneratedTimestamp(): void
    {
        $evaluation = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false
        );

        $this->assertGreaterThan(0, $evaluation->timestamp);
    }

    public function testConstructWithExplicitTimestamp(): void
    {
        $explicitTimestamp = 1234567890.123456;

        $evaluation = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false,
            $explicitTimestamp
        );

        $this->assertSame($explicitTimestamp, $evaluation->timestamp);
    }

    // Timestamp Behavior Tests

    public function testAutoTimestampIsReasonable(): void
    {
        $before = microtime(true);
        $evaluation = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false
        );
        $after = microtime(true);

        $this->assertGreaterThanOrEqual($before, $evaluation->timestamp);
        $this->assertLessThanOrEqual($after, $evaluation->timestamp);
    }

    public function testExplicitTimestampPreserved(): void
    {
        $explicitTimestamp = 1609459200.987654; // 2021-01-01 00:00:00.987654

        $evaluation = new GateEvaluation(
            $this->mockGate,
            GateResult::DENY,
            true,
            $explicitTimestamp
        );

        $this->assertSame($explicitTimestamp, $evaluation->timestamp, 'Explicit timestamp should be preserved exactly');
    }

    public function testMultipleInstancesHaveDifferentTimestamps(): void
    {
        $evaluation1 = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false
        );

        // Small delay to ensure different timestamps
        usleep(100); // 0.0001 seconds

        $evaluation2 = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false
        );

        $this->assertNotEquals(
            $evaluation1->timestamp,
            $evaluation2->timestamp,
            'Auto-generated timestamps should differ for instances created at different times'
        );
        $this->assertLessThan($evaluation2->timestamp, $evaluation1->timestamp);
    }

    // Readonly Immutability Tests

    public function testAllPropertiesArePublic(): void
    {
        $evaluation = new GateEvaluation(
            $this->mockGate,
            GateResult::ALLOW,
            false
        );

        // Should be able to read all properties
        $this->assertInstanceOf(Gate::class, $evaluation->gate);
        $this->assertSame(GateResult::ALLOW, $evaluation->result);
        $this->assertFalse($evaluation->isActionGate);
        $this->assertGreaterThan(0, $evaluation->timestamp);
    }

    public function testIsReadonlyClass(): void
    {
        $reflection = new ReflectionClass(GateEvaluation::class);

        $this->assertTrue(
            $reflection->isReadOnly(),
            'GateEvaluation should be a readonly class'
        );
    }
}
